### ISSUE TITLE
Crop with AI

### ISSUE THREAD

**Issue by WaqarKhalid** [ZaidPathan/ZImageCropper#2]
What if I want to crop the image with some artificial intelligence as in your example some outer part of the car is also cropped along with the the image that we want to crop.That remaining part should be trimmed and if I want to touch on the parts of the car like I don't want to drag my finger along the boundry of the image because in that case some part of the outer image will also be cropped so it there should be some way to select the part of the image to be cropped with some intelligence

**Comment by ZaidPathan** [comment]
Try Following steps,

Step 1: Add ZImageCropper.swift file to your project.
Step 2: Crop image using following,

 ```
let croppedImage = ZImageCropper.cropImage(ofImageView: tempImageView, withinPoints: [
            CGPoint(x: 0, y: 0),
            CGPoint(x: 100, y: 0),
            CGPoint(x: 100, y: 100),
            CGPoint(x: 0, y: 100)
            ])
```

Note : Make sure you provide valid points, points must be >=2 in count.
