### ISSUE TITLE
Ability to remove the background

### ISSUE THREAD

**Issue by anonrig** [ZaidPathan/ZImageCropper#5]
First of all, thank you for this repository. I'm having an issue related to after crop. If the CGShapeLayer is smaller than the imageView of the original image, the outside parts are transparent, and after the following code, I couldn't remove the background either, and select the smallest section of the image.

```swift    
    func cropImage() {
        if path.isEmpty {
            return
        }
        
        shapeLayer.fillColor = UIColor.black.cgColor
        viewSource.imageView.layer.mask = shapeLayer
        viewSource.imageView.layer.masksToBounds = true

        UIGraphicsBeginImageContextWithOptions(viewSource.imageView.bounds.size, false, UIScreen.main.scale)
        viewSource.imageView.layer.render(in: UIGraphicsGetCurrentContext()!)
        let newImage = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()

        self.completionObservable.onNext(newImage)
    }
```

If I add this newImage to another imageview and show it, I still see the transparent layers and not just the cropped area itself.

Example: 

![simulator screen shot - iphone xr - 2019-02-25 at 00 53 47](https://user-images.githubusercontent.com/1935246/53306223-737a6c00-389b-11e9-8617-963cd9e69b23.png)

**Comment by Iccr** [comment]
any update in this. or any workarounds ?

**Comment by anonrig** [comment]
remove alpha layer from the screenshot using a image processing lib
